# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-20 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
        ('trade', '0002_auto_20191127_1113'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='shoppingcart',
            index_together=set([('user', 'goods')]),
        ),
    ]
