# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20191205_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(blank=True, help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
